export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const SET_PRODUCT_CATEGORY = 'SET_PRODUCT_CATEGORY';
export const SET_PRODUCT_COLOR = 'SET_PRODUCT_COLOR';

export const SET_PRIMARY_ITEM = 'SET_PRIMARY_ITEM';

export const RESET_ALL_FILTERS = 'RESET_ALL_FILTERS';
